/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SampleRouteImport } from './routes/sample'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyIdentityIndexRouteImport } from './routes/verify-identity/index'
import { Route as UserProfileIndexRouteImport } from './routes/user-profile/index'
import { Route as UpdatePhoneIndexRouteImport } from './routes/update-phone/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ReferAndEarnIndexRouteImport } from './routes/refer-and-earn/index'
import { Route as PaymentMethodsIndexRouteImport } from './routes/payment-methods/index'
import { Route as PayLoanIndexRouteImport } from './routes/pay-loan/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as LoanApplicationIndexRouteImport } from './routes/loan-application/index'
import { Route as HelpCenterIndexRouteImport } from './routes/help-center/index'
import { Route as DeleteAccountIndexRouteImport } from './routes/delete-account/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CalculatorIndexRouteImport } from './routes/calculator/index'
import { Route as AddPhoneNumberIndexRouteImport } from './routes/add-phone-number/index'
import { Route as VerifyIdentityVerifyPersonalDetailsRouteImport } from './routes/verify-identity/verify-personal-details'
import { Route as VerifyIdentityIdentityVerifiedRouteImport } from './routes/verify-identity/identity-verified'
import { Route as VerifyIdentityIdDetailsRouteImport } from './routes/verify-identity/id-details'
import { Route as VerifyIdentityFrontIdVerificationRouteImport } from './routes/verify-identity/front-id-verification'
import { Route as VerifyIdentityFaceVerificationRouteImport } from './routes/verify-identity/face-verification'
import { Route as VerifyIdentityChooseIdRouteImport } from './routes/verify-identity/choose-id'
import { Route as VerifyIdentityBackIdVerificationRouteImport } from './routes/verify-identity/back-id-verification'
import { Route as UpdatePhoneVerifyPhoneRouteImport } from './routes/update-phone/verify-phone'
import { Route as UpdatePhoneNumberVerifiedRouteImport } from './routes/update-phone/number-verified'
import { Route as TopUpTopUpMainRouteImport } from './routes/top-up/top-up-main'
import { Route as TokuenInfoTermsAndConditionsRouteImport } from './routes/tokuen-info/terms-and-conditions'
import { Route as TokuenInfoPrivacyPolicyRouteImport } from './routes/tokuen-info/privacy-policy'
import { Route as QrScannerScanRouteImport } from './routes/qr-scanner/scan'
import { Route as PaymentMethodsCardAddedRouteImport } from './routes/payment-methods/card-added'
import { Route as PaymentMethodsAddCardRouteImport } from './routes/payment-methods/add-card'
import { Route as PayLoanReviewDetailsRouteImport } from './routes/pay-loan/review-details'
import { Route as PayLoanPayThroughRouteImport } from './routes/pay-loan/pay-through'
import { Route as PayLoanLoanPaidRouteImport } from './routes/pay-loan/loan-paid'
import { Route as NotificationsEmptyRouteImport } from './routes/notifications/empty'
import { Route as LoansLoanListRouteImport } from './routes/loans/loan-list'
import { Route as LoanApplicationLoanDetailsRouteImport } from './routes/loan-application/loan-details'
import { Route as LoanApplicationLoanApprovedRouteImport } from './routes/loan-application/loan-approved'
import { Route as LoanApplicationChooseEmiRouteImport } from './routes/loan-application/choose-emi'
import { Route as DeleteAccountDeleteUsingPhoneRouteImport } from './routes/delete-account/delete-using-phone'
import { Route as DeleteAccountAccountDeletedRouteImport } from './routes/delete-account/account-deleted'
import { Route as BillsPaymentPaymentMainRouteImport } from './routes/bills-payment/payment-main'
import { Route as AddPhoneNumberPhoneNumberAddedRouteImport } from './routes/add-phone-number/phone-number-added'
import { Route as AuthenticationVerifyEmailIndexRouteImport } from './routes/authentication/verify-email/index'
import { Route as AuthenticationRegistrationIndexRouteImport } from './routes/authentication/registration/index'
import { Route as AuthenticationForgotPasswordIndexRouteImport } from './routes/authentication/forgot-password/index'
import { Route as AuthenticationVerifyEmailEmailVerifiedRouteImport } from './routes/authentication/verify-email/email-verified'
import { Route as AuthenticationRegistrationCreatePasswordRouteImport } from './routes/authentication/registration/create-password'
import { Route as AuthenticationRegistrationAccountCreatedRouteImport } from './routes/authentication/registration/account-created'
import { Route as AuthenticationForgotPasswordPasswordChangedRouteImport } from './routes/authentication/forgot-password/password-changed'
import { Route as AuthenticationForgotPasswordForgotPassword1RouteImport } from './routes/authentication/forgot-password/forgot-password-1'

const SampleRoute = SampleRouteImport.update({
  id: '/sample',
  path: '/sample',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdentityIndexRoute = VerifyIdentityIndexRouteImport.update({
  id: '/verify-identity/',
  path: '/verify-identity/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileIndexRoute = UserProfileIndexRouteImport.update({
  id: '/user-profile/',
  path: '/user-profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePhoneIndexRoute = UpdatePhoneIndexRouteImport.update({
  id: '/update-phone/',
  path: '/update-phone/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferAndEarnIndexRoute = ReferAndEarnIndexRouteImport.update({
  id: '/refer-and-earn/',
  path: '/refer-and-earn/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsIndexRoute = PaymentMethodsIndexRouteImport.update({
  id: '/payment-methods/',
  path: '/payment-methods/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayLoanIndexRoute = PayLoanIndexRouteImport.update({
  id: '/pay-loan/',
  path: '/pay-loan/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanApplicationIndexRoute = LoanApplicationIndexRouteImport.update({
  id: '/loan-application/',
  path: '/loan-application/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterIndexRoute = HelpCenterIndexRouteImport.update({
  id: '/help-center/',
  path: '/help-center/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountIndexRoute = DeleteAccountIndexRouteImport.update({
  id: '/delete-account/',
  path: '/delete-account/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorIndexRoute = CalculatorIndexRouteImport.update({
  id: '/calculator/',
  path: '/calculator/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPhoneNumberIndexRoute = AddPhoneNumberIndexRouteImport.update({
  id: '/add-phone-number/',
  path: '/add-phone-number/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdentityVerifyPersonalDetailsRoute =
  VerifyIdentityVerifyPersonalDetailsRouteImport.update({
    id: '/verify-identity/verify-personal-details',
    path: '/verify-identity/verify-personal-details',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerifyIdentityIdentityVerifiedRoute =
  VerifyIdentityIdentityVerifiedRouteImport.update({
    id: '/verify-identity/identity-verified',
    path: '/verify-identity/identity-verified',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerifyIdentityIdDetailsRoute = VerifyIdentityIdDetailsRouteImport.update({
  id: '/verify-identity/id-details',
  path: '/verify-identity/id-details',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdentityFrontIdVerificationRoute =
  VerifyIdentityFrontIdVerificationRouteImport.update({
    id: '/verify-identity/front-id-verification',
    path: '/verify-identity/front-id-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerifyIdentityFaceVerificationRoute =
  VerifyIdentityFaceVerificationRouteImport.update({
    id: '/verify-identity/face-verification',
    path: '/verify-identity/face-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerifyIdentityChooseIdRoute = VerifyIdentityChooseIdRouteImport.update({
  id: '/verify-identity/choose-id',
  path: '/verify-identity/choose-id',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdentityBackIdVerificationRoute =
  VerifyIdentityBackIdVerificationRouteImport.update({
    id: '/verify-identity/back-id-verification',
    path: '/verify-identity/back-id-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const UpdatePhoneVerifyPhoneRoute = UpdatePhoneVerifyPhoneRouteImport.update({
  id: '/update-phone/verify-phone',
  path: '/update-phone/verify-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePhoneNumberVerifiedRoute =
  UpdatePhoneNumberVerifiedRouteImport.update({
    id: '/update-phone/number-verified',
    path: '/update-phone/number-verified',
    getParentRoute: () => rootRouteImport,
  } as any)
const TopUpTopUpMainRoute = TopUpTopUpMainRouteImport.update({
  id: '/top-up/top-up-main',
  path: '/top-up/top-up-main',
  getParentRoute: () => rootRouteImport,
} as any)
const TokuenInfoTermsAndConditionsRoute =
  TokuenInfoTermsAndConditionsRouteImport.update({
    id: '/tokuen-info/terms-and-conditions',
    path: '/tokuen-info/terms-and-conditions',
    getParentRoute: () => rootRouteImport,
  } as any)
const TokuenInfoPrivacyPolicyRoute = TokuenInfoPrivacyPolicyRouteImport.update({
  id: '/tokuen-info/privacy-policy',
  path: '/tokuen-info/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const QrScannerScanRoute = QrScannerScanRouteImport.update({
  id: '/qr-scanner/scan',
  path: '/qr-scanner/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsCardAddedRoute = PaymentMethodsCardAddedRouteImport.update({
  id: '/payment-methods/card-added',
  path: '/payment-methods/card-added',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsAddCardRoute = PaymentMethodsAddCardRouteImport.update({
  id: '/payment-methods/add-card',
  path: '/payment-methods/add-card',
  getParentRoute: () => rootRouteImport,
} as any)
const PayLoanReviewDetailsRoute = PayLoanReviewDetailsRouteImport.update({
  id: '/pay-loan/review-details',
  path: '/pay-loan/review-details',
  getParentRoute: () => rootRouteImport,
} as any)
const PayLoanPayThroughRoute = PayLoanPayThroughRouteImport.update({
  id: '/pay-loan/pay-through',
  path: '/pay-loan/pay-through',
  getParentRoute: () => rootRouteImport,
} as any)
const PayLoanLoanPaidRoute = PayLoanLoanPaidRouteImport.update({
  id: '/pay-loan/loan-paid',
  path: '/pay-loan/loan-paid',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsEmptyRoute = NotificationsEmptyRouteImport.update({
  id: '/notifications/empty',
  path: '/notifications/empty',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansLoanListRoute = LoansLoanListRouteImport.update({
  id: '/loans/loan-list',
  path: '/loans/loan-list',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanApplicationLoanDetailsRoute =
  LoanApplicationLoanDetailsRouteImport.update({
    id: '/loan-application/loan-details',
    path: '/loan-application/loan-details',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoanApplicationLoanApprovedRoute =
  LoanApplicationLoanApprovedRouteImport.update({
    id: '/loan-application/loan-approved',
    path: '/loan-application/loan-approved',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoanApplicationChooseEmiRoute =
  LoanApplicationChooseEmiRouteImport.update({
    id: '/loan-application/choose-emi',
    path: '/loan-application/choose-emi',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeleteAccountDeleteUsingPhoneRoute =
  DeleteAccountDeleteUsingPhoneRouteImport.update({
    id: '/delete-account/delete-using-phone',
    path: '/delete-account/delete-using-phone',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeleteAccountAccountDeletedRoute =
  DeleteAccountAccountDeletedRouteImport.update({
    id: '/delete-account/account-deleted',
    path: '/delete-account/account-deleted',
    getParentRoute: () => rootRouteImport,
  } as any)
const BillsPaymentPaymentMainRoute = BillsPaymentPaymentMainRouteImport.update({
  id: '/bills-payment/payment-main',
  path: '/bills-payment/payment-main',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPhoneNumberPhoneNumberAddedRoute =
  AddPhoneNumberPhoneNumberAddedRouteImport.update({
    id: '/add-phone-number/phone-number-added',
    path: '/add-phone-number/phone-number-added',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticationVerifyEmailIndexRoute =
  AuthenticationVerifyEmailIndexRouteImport.update({
    id: '/authentication/verify-email/',
    path: '/authentication/verify-email/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticationRegistrationIndexRoute =
  AuthenticationRegistrationIndexRouteImport.update({
    id: '/authentication/registration/',
    path: '/authentication/registration/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticationForgotPasswordIndexRoute =
  AuthenticationForgotPasswordIndexRouteImport.update({
    id: '/authentication/forgot-password/',
    path: '/authentication/forgot-password/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticationVerifyEmailEmailVerifiedRoute =
  AuthenticationVerifyEmailEmailVerifiedRouteImport.update({
    id: '/authentication/verify-email/email-verified',
    path: '/authentication/verify-email/email-verified',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticationRegistrationCreatePasswordRoute =
  AuthenticationRegistrationCreatePasswordRouteImport.update({
    id: '/authentication/registration/create-password',
    path: '/authentication/registration/create-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticationRegistrationAccountCreatedRoute =
  AuthenticationRegistrationAccountCreatedRouteImport.update({
    id: '/authentication/registration/account-created',
    path: '/authentication/registration/account-created',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticationForgotPasswordPasswordChangedRoute =
  AuthenticationForgotPasswordPasswordChangedRouteImport.update({
    id: '/authentication/forgot-password/password-changed',
    path: '/authentication/forgot-password/password-changed',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticationForgotPasswordForgotPassword1Route =
  AuthenticationForgotPasswordForgotPassword1RouteImport.update({
    id: '/authentication/forgot-password/forgot-password-1',
    path: '/authentication/forgot-password/forgot-password-1',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sample': typeof SampleRoute
  '/add-phone-number/phone-number-added': typeof AddPhoneNumberPhoneNumberAddedRoute
  '/bills-payment/payment-main': typeof BillsPaymentPaymentMainRoute
  '/delete-account/account-deleted': typeof DeleteAccountAccountDeletedRoute
  '/delete-account/delete-using-phone': typeof DeleteAccountDeleteUsingPhoneRoute
  '/loan-application/choose-emi': typeof LoanApplicationChooseEmiRoute
  '/loan-application/loan-approved': typeof LoanApplicationLoanApprovedRoute
  '/loan-application/loan-details': typeof LoanApplicationLoanDetailsRoute
  '/loans/loan-list': typeof LoansLoanListRoute
  '/notifications/empty': typeof NotificationsEmptyRoute
  '/pay-loan/loan-paid': typeof PayLoanLoanPaidRoute
  '/pay-loan/pay-through': typeof PayLoanPayThroughRoute
  '/pay-loan/review-details': typeof PayLoanReviewDetailsRoute
  '/payment-methods/add-card': typeof PaymentMethodsAddCardRoute
  '/payment-methods/card-added': typeof PaymentMethodsCardAddedRoute
  '/qr-scanner/scan': typeof QrScannerScanRoute
  '/tokuen-info/privacy-policy': typeof TokuenInfoPrivacyPolicyRoute
  '/tokuen-info/terms-and-conditions': typeof TokuenInfoTermsAndConditionsRoute
  '/top-up/top-up-main': typeof TopUpTopUpMainRoute
  '/update-phone/number-verified': typeof UpdatePhoneNumberVerifiedRoute
  '/update-phone/verify-phone': typeof UpdatePhoneVerifyPhoneRoute
  '/verify-identity/back-id-verification': typeof VerifyIdentityBackIdVerificationRoute
  '/verify-identity/choose-id': typeof VerifyIdentityChooseIdRoute
  '/verify-identity/face-verification': typeof VerifyIdentityFaceVerificationRoute
  '/verify-identity/front-id-verification': typeof VerifyIdentityFrontIdVerificationRoute
  '/verify-identity/id-details': typeof VerifyIdentityIdDetailsRoute
  '/verify-identity/identity-verified': typeof VerifyIdentityIdentityVerifiedRoute
  '/verify-identity/verify-personal-details': typeof VerifyIdentityVerifyPersonalDetailsRoute
  '/add-phone-number': typeof AddPhoneNumberIndexRoute
  '/calculator': typeof CalculatorIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/delete-account': typeof DeleteAccountIndexRoute
  '/help-center': typeof HelpCenterIndexRoute
  '/loan-application': typeof LoanApplicationIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/pay-loan': typeof PayLoanIndexRoute
  '/payment-methods': typeof PaymentMethodsIndexRoute
  '/refer-and-earn': typeof ReferAndEarnIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/update-phone': typeof UpdatePhoneIndexRoute
  '/user-profile': typeof UserProfileIndexRoute
  '/verify-identity': typeof VerifyIdentityIndexRoute
  '/authentication/forgot-password/forgot-password-1': typeof AuthenticationForgotPasswordForgotPassword1Route
  '/authentication/forgot-password/password-changed': typeof AuthenticationForgotPasswordPasswordChangedRoute
  '/authentication/registration/account-created': typeof AuthenticationRegistrationAccountCreatedRoute
  '/authentication/registration/create-password': typeof AuthenticationRegistrationCreatePasswordRoute
  '/authentication/verify-email/email-verified': typeof AuthenticationVerifyEmailEmailVerifiedRoute
  '/authentication/forgot-password': typeof AuthenticationForgotPasswordIndexRoute
  '/authentication/registration': typeof AuthenticationRegistrationIndexRoute
  '/authentication/verify-email': typeof AuthenticationVerifyEmailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sample': typeof SampleRoute
  '/add-phone-number/phone-number-added': typeof AddPhoneNumberPhoneNumberAddedRoute
  '/bills-payment/payment-main': typeof BillsPaymentPaymentMainRoute
  '/delete-account/account-deleted': typeof DeleteAccountAccountDeletedRoute
  '/delete-account/delete-using-phone': typeof DeleteAccountDeleteUsingPhoneRoute
  '/loan-application/choose-emi': typeof LoanApplicationChooseEmiRoute
  '/loan-application/loan-approved': typeof LoanApplicationLoanApprovedRoute
  '/loan-application/loan-details': typeof LoanApplicationLoanDetailsRoute
  '/loans/loan-list': typeof LoansLoanListRoute
  '/notifications/empty': typeof NotificationsEmptyRoute
  '/pay-loan/loan-paid': typeof PayLoanLoanPaidRoute
  '/pay-loan/pay-through': typeof PayLoanPayThroughRoute
  '/pay-loan/review-details': typeof PayLoanReviewDetailsRoute
  '/payment-methods/add-card': typeof PaymentMethodsAddCardRoute
  '/payment-methods/card-added': typeof PaymentMethodsCardAddedRoute
  '/qr-scanner/scan': typeof QrScannerScanRoute
  '/tokuen-info/privacy-policy': typeof TokuenInfoPrivacyPolicyRoute
  '/tokuen-info/terms-and-conditions': typeof TokuenInfoTermsAndConditionsRoute
  '/top-up/top-up-main': typeof TopUpTopUpMainRoute
  '/update-phone/number-verified': typeof UpdatePhoneNumberVerifiedRoute
  '/update-phone/verify-phone': typeof UpdatePhoneVerifyPhoneRoute
  '/verify-identity/back-id-verification': typeof VerifyIdentityBackIdVerificationRoute
  '/verify-identity/choose-id': typeof VerifyIdentityChooseIdRoute
  '/verify-identity/face-verification': typeof VerifyIdentityFaceVerificationRoute
  '/verify-identity/front-id-verification': typeof VerifyIdentityFrontIdVerificationRoute
  '/verify-identity/id-details': typeof VerifyIdentityIdDetailsRoute
  '/verify-identity/identity-verified': typeof VerifyIdentityIdentityVerifiedRoute
  '/verify-identity/verify-personal-details': typeof VerifyIdentityVerifyPersonalDetailsRoute
  '/add-phone-number': typeof AddPhoneNumberIndexRoute
  '/calculator': typeof CalculatorIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/delete-account': typeof DeleteAccountIndexRoute
  '/help-center': typeof HelpCenterIndexRoute
  '/loan-application': typeof LoanApplicationIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/pay-loan': typeof PayLoanIndexRoute
  '/payment-methods': typeof PaymentMethodsIndexRoute
  '/refer-and-earn': typeof ReferAndEarnIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/update-phone': typeof UpdatePhoneIndexRoute
  '/user-profile': typeof UserProfileIndexRoute
  '/verify-identity': typeof VerifyIdentityIndexRoute
  '/authentication/forgot-password/forgot-password-1': typeof AuthenticationForgotPasswordForgotPassword1Route
  '/authentication/forgot-password/password-changed': typeof AuthenticationForgotPasswordPasswordChangedRoute
  '/authentication/registration/account-created': typeof AuthenticationRegistrationAccountCreatedRoute
  '/authentication/registration/create-password': typeof AuthenticationRegistrationCreatePasswordRoute
  '/authentication/verify-email/email-verified': typeof AuthenticationVerifyEmailEmailVerifiedRoute
  '/authentication/forgot-password': typeof AuthenticationForgotPasswordIndexRoute
  '/authentication/registration': typeof AuthenticationRegistrationIndexRoute
  '/authentication/verify-email': typeof AuthenticationVerifyEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sample': typeof SampleRoute
  '/add-phone-number/phone-number-added': typeof AddPhoneNumberPhoneNumberAddedRoute
  '/bills-payment/payment-main': typeof BillsPaymentPaymentMainRoute
  '/delete-account/account-deleted': typeof DeleteAccountAccountDeletedRoute
  '/delete-account/delete-using-phone': typeof DeleteAccountDeleteUsingPhoneRoute
  '/loan-application/choose-emi': typeof LoanApplicationChooseEmiRoute
  '/loan-application/loan-approved': typeof LoanApplicationLoanApprovedRoute
  '/loan-application/loan-details': typeof LoanApplicationLoanDetailsRoute
  '/loans/loan-list': typeof LoansLoanListRoute
  '/notifications/empty': typeof NotificationsEmptyRoute
  '/pay-loan/loan-paid': typeof PayLoanLoanPaidRoute
  '/pay-loan/pay-through': typeof PayLoanPayThroughRoute
  '/pay-loan/review-details': typeof PayLoanReviewDetailsRoute
  '/payment-methods/add-card': typeof PaymentMethodsAddCardRoute
  '/payment-methods/card-added': typeof PaymentMethodsCardAddedRoute
  '/qr-scanner/scan': typeof QrScannerScanRoute
  '/tokuen-info/privacy-policy': typeof TokuenInfoPrivacyPolicyRoute
  '/tokuen-info/terms-and-conditions': typeof TokuenInfoTermsAndConditionsRoute
  '/top-up/top-up-main': typeof TopUpTopUpMainRoute
  '/update-phone/number-verified': typeof UpdatePhoneNumberVerifiedRoute
  '/update-phone/verify-phone': typeof UpdatePhoneVerifyPhoneRoute
  '/verify-identity/back-id-verification': typeof VerifyIdentityBackIdVerificationRoute
  '/verify-identity/choose-id': typeof VerifyIdentityChooseIdRoute
  '/verify-identity/face-verification': typeof VerifyIdentityFaceVerificationRoute
  '/verify-identity/front-id-verification': typeof VerifyIdentityFrontIdVerificationRoute
  '/verify-identity/id-details': typeof VerifyIdentityIdDetailsRoute
  '/verify-identity/identity-verified': typeof VerifyIdentityIdentityVerifiedRoute
  '/verify-identity/verify-personal-details': typeof VerifyIdentityVerifyPersonalDetailsRoute
  '/add-phone-number/': typeof AddPhoneNumberIndexRoute
  '/calculator/': typeof CalculatorIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/delete-account/': typeof DeleteAccountIndexRoute
  '/help-center/': typeof HelpCenterIndexRoute
  '/loan-application/': typeof LoanApplicationIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/pay-loan/': typeof PayLoanIndexRoute
  '/payment-methods/': typeof PaymentMethodsIndexRoute
  '/refer-and-earn/': typeof ReferAndEarnIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/update-phone/': typeof UpdatePhoneIndexRoute
  '/user-profile/': typeof UserProfileIndexRoute
  '/verify-identity/': typeof VerifyIdentityIndexRoute
  '/authentication/forgot-password/forgot-password-1': typeof AuthenticationForgotPasswordForgotPassword1Route
  '/authentication/forgot-password/password-changed': typeof AuthenticationForgotPasswordPasswordChangedRoute
  '/authentication/registration/account-created': typeof AuthenticationRegistrationAccountCreatedRoute
  '/authentication/registration/create-password': typeof AuthenticationRegistrationCreatePasswordRoute
  '/authentication/verify-email/email-verified': typeof AuthenticationVerifyEmailEmailVerifiedRoute
  '/authentication/forgot-password/': typeof AuthenticationForgotPasswordIndexRoute
  '/authentication/registration/': typeof AuthenticationRegistrationIndexRoute
  '/authentication/verify-email/': typeof AuthenticationVerifyEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sample'
    | '/add-phone-number/phone-number-added'
    | '/bills-payment/payment-main'
    | '/delete-account/account-deleted'
    | '/delete-account/delete-using-phone'
    | '/loan-application/choose-emi'
    | '/loan-application/loan-approved'
    | '/loan-application/loan-details'
    | '/loans/loan-list'
    | '/notifications/empty'
    | '/pay-loan/loan-paid'
    | '/pay-loan/pay-through'
    | '/pay-loan/review-details'
    | '/payment-methods/add-card'
    | '/payment-methods/card-added'
    | '/qr-scanner/scan'
    | '/tokuen-info/privacy-policy'
    | '/tokuen-info/terms-and-conditions'
    | '/top-up/top-up-main'
    | '/update-phone/number-verified'
    | '/update-phone/verify-phone'
    | '/verify-identity/back-id-verification'
    | '/verify-identity/choose-id'
    | '/verify-identity/face-verification'
    | '/verify-identity/front-id-verification'
    | '/verify-identity/id-details'
    | '/verify-identity/identity-verified'
    | '/verify-identity/verify-personal-details'
    | '/add-phone-number'
    | '/calculator'
    | '/dashboard'
    | '/delete-account'
    | '/help-center'
    | '/loan-application'
    | '/notifications'
    | '/pay-loan'
    | '/payment-methods'
    | '/refer-and-earn'
    | '/settings'
    | '/update-phone'
    | '/user-profile'
    | '/verify-identity'
    | '/authentication/forgot-password/forgot-password-1'
    | '/authentication/forgot-password/password-changed'
    | '/authentication/registration/account-created'
    | '/authentication/registration/create-password'
    | '/authentication/verify-email/email-verified'
    | '/authentication/forgot-password'
    | '/authentication/registration'
    | '/authentication/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sample'
    | '/add-phone-number/phone-number-added'
    | '/bills-payment/payment-main'
    | '/delete-account/account-deleted'
    | '/delete-account/delete-using-phone'
    | '/loan-application/choose-emi'
    | '/loan-application/loan-approved'
    | '/loan-application/loan-details'
    | '/loans/loan-list'
    | '/notifications/empty'
    | '/pay-loan/loan-paid'
    | '/pay-loan/pay-through'
    | '/pay-loan/review-details'
    | '/payment-methods/add-card'
    | '/payment-methods/card-added'
    | '/qr-scanner/scan'
    | '/tokuen-info/privacy-policy'
    | '/tokuen-info/terms-and-conditions'
    | '/top-up/top-up-main'
    | '/update-phone/number-verified'
    | '/update-phone/verify-phone'
    | '/verify-identity/back-id-verification'
    | '/verify-identity/choose-id'
    | '/verify-identity/face-verification'
    | '/verify-identity/front-id-verification'
    | '/verify-identity/id-details'
    | '/verify-identity/identity-verified'
    | '/verify-identity/verify-personal-details'
    | '/add-phone-number'
    | '/calculator'
    | '/dashboard'
    | '/delete-account'
    | '/help-center'
    | '/loan-application'
    | '/notifications'
    | '/pay-loan'
    | '/payment-methods'
    | '/refer-and-earn'
    | '/settings'
    | '/update-phone'
    | '/user-profile'
    | '/verify-identity'
    | '/authentication/forgot-password/forgot-password-1'
    | '/authentication/forgot-password/password-changed'
    | '/authentication/registration/account-created'
    | '/authentication/registration/create-password'
    | '/authentication/verify-email/email-verified'
    | '/authentication/forgot-password'
    | '/authentication/registration'
    | '/authentication/verify-email'
  id:
    | '__root__'
    | '/'
    | '/sample'
    | '/add-phone-number/phone-number-added'
    | '/bills-payment/payment-main'
    | '/delete-account/account-deleted'
    | '/delete-account/delete-using-phone'
    | '/loan-application/choose-emi'
    | '/loan-application/loan-approved'
    | '/loan-application/loan-details'
    | '/loans/loan-list'
    | '/notifications/empty'
    | '/pay-loan/loan-paid'
    | '/pay-loan/pay-through'
    | '/pay-loan/review-details'
    | '/payment-methods/add-card'
    | '/payment-methods/card-added'
    | '/qr-scanner/scan'
    | '/tokuen-info/privacy-policy'
    | '/tokuen-info/terms-and-conditions'
    | '/top-up/top-up-main'
    | '/update-phone/number-verified'
    | '/update-phone/verify-phone'
    | '/verify-identity/back-id-verification'
    | '/verify-identity/choose-id'
    | '/verify-identity/face-verification'
    | '/verify-identity/front-id-verification'
    | '/verify-identity/id-details'
    | '/verify-identity/identity-verified'
    | '/verify-identity/verify-personal-details'
    | '/add-phone-number/'
    | '/calculator/'
    | '/dashboard/'
    | '/delete-account/'
    | '/help-center/'
    | '/loan-application/'
    | '/notifications/'
    | '/pay-loan/'
    | '/payment-methods/'
    | '/refer-and-earn/'
    | '/settings/'
    | '/update-phone/'
    | '/user-profile/'
    | '/verify-identity/'
    | '/authentication/forgot-password/forgot-password-1'
    | '/authentication/forgot-password/password-changed'
    | '/authentication/registration/account-created'
    | '/authentication/registration/create-password'
    | '/authentication/verify-email/email-verified'
    | '/authentication/forgot-password/'
    | '/authentication/registration/'
    | '/authentication/verify-email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SampleRoute: typeof SampleRoute
  AddPhoneNumberPhoneNumberAddedRoute: typeof AddPhoneNumberPhoneNumberAddedRoute
  BillsPaymentPaymentMainRoute: typeof BillsPaymentPaymentMainRoute
  DeleteAccountAccountDeletedRoute: typeof DeleteAccountAccountDeletedRoute
  DeleteAccountDeleteUsingPhoneRoute: typeof DeleteAccountDeleteUsingPhoneRoute
  LoanApplicationChooseEmiRoute: typeof LoanApplicationChooseEmiRoute
  LoanApplicationLoanApprovedRoute: typeof LoanApplicationLoanApprovedRoute
  LoanApplicationLoanDetailsRoute: typeof LoanApplicationLoanDetailsRoute
  LoansLoanListRoute: typeof LoansLoanListRoute
  NotificationsEmptyRoute: typeof NotificationsEmptyRoute
  PayLoanLoanPaidRoute: typeof PayLoanLoanPaidRoute
  PayLoanPayThroughRoute: typeof PayLoanPayThroughRoute
  PayLoanReviewDetailsRoute: typeof PayLoanReviewDetailsRoute
  PaymentMethodsAddCardRoute: typeof PaymentMethodsAddCardRoute
  PaymentMethodsCardAddedRoute: typeof PaymentMethodsCardAddedRoute
  QrScannerScanRoute: typeof QrScannerScanRoute
  TokuenInfoPrivacyPolicyRoute: typeof TokuenInfoPrivacyPolicyRoute
  TokuenInfoTermsAndConditionsRoute: typeof TokuenInfoTermsAndConditionsRoute
  TopUpTopUpMainRoute: typeof TopUpTopUpMainRoute
  UpdatePhoneNumberVerifiedRoute: typeof UpdatePhoneNumberVerifiedRoute
  UpdatePhoneVerifyPhoneRoute: typeof UpdatePhoneVerifyPhoneRoute
  VerifyIdentityBackIdVerificationRoute: typeof VerifyIdentityBackIdVerificationRoute
  VerifyIdentityChooseIdRoute: typeof VerifyIdentityChooseIdRoute
  VerifyIdentityFaceVerificationRoute: typeof VerifyIdentityFaceVerificationRoute
  VerifyIdentityFrontIdVerificationRoute: typeof VerifyIdentityFrontIdVerificationRoute
  VerifyIdentityIdDetailsRoute: typeof VerifyIdentityIdDetailsRoute
  VerifyIdentityIdentityVerifiedRoute: typeof VerifyIdentityIdentityVerifiedRoute
  VerifyIdentityVerifyPersonalDetailsRoute: typeof VerifyIdentityVerifyPersonalDetailsRoute
  AddPhoneNumberIndexRoute: typeof AddPhoneNumberIndexRoute
  CalculatorIndexRoute: typeof CalculatorIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DeleteAccountIndexRoute: typeof DeleteAccountIndexRoute
  HelpCenterIndexRoute: typeof HelpCenterIndexRoute
  LoanApplicationIndexRoute: typeof LoanApplicationIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  PayLoanIndexRoute: typeof PayLoanIndexRoute
  PaymentMethodsIndexRoute: typeof PaymentMethodsIndexRoute
  ReferAndEarnIndexRoute: typeof ReferAndEarnIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  UpdatePhoneIndexRoute: typeof UpdatePhoneIndexRoute
  UserProfileIndexRoute: typeof UserProfileIndexRoute
  VerifyIdentityIndexRoute: typeof VerifyIdentityIndexRoute
  AuthenticationForgotPasswordForgotPassword1Route: typeof AuthenticationForgotPasswordForgotPassword1Route
  AuthenticationForgotPasswordPasswordChangedRoute: typeof AuthenticationForgotPasswordPasswordChangedRoute
  AuthenticationRegistrationAccountCreatedRoute: typeof AuthenticationRegistrationAccountCreatedRoute
  AuthenticationRegistrationCreatePasswordRoute: typeof AuthenticationRegistrationCreatePasswordRoute
  AuthenticationVerifyEmailEmailVerifiedRoute: typeof AuthenticationVerifyEmailEmailVerifiedRoute
  AuthenticationForgotPasswordIndexRoute: typeof AuthenticationForgotPasswordIndexRoute
  AuthenticationRegistrationIndexRoute: typeof AuthenticationRegistrationIndexRoute
  AuthenticationVerifyEmailIndexRoute: typeof AuthenticationVerifyEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sample': {
      id: '/sample'
      path: '/sample'
      fullPath: '/sample'
      preLoaderRoute: typeof SampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-identity/': {
      id: '/verify-identity/'
      path: '/verify-identity'
      fullPath: '/verify-identity'
      preLoaderRoute: typeof VerifyIdentityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-profile/': {
      id: '/user-profile/'
      path: '/user-profile'
      fullPath: '/user-profile'
      preLoaderRoute: typeof UserProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-phone/': {
      id: '/update-phone/'
      path: '/update-phone'
      fullPath: '/update-phone'
      preLoaderRoute: typeof UpdatePhoneIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer-and-earn/': {
      id: '/refer-and-earn/'
      path: '/refer-and-earn'
      fullPath: '/refer-and-earn'
      preLoaderRoute: typeof ReferAndEarnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods/': {
      id: '/payment-methods/'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-loan/': {
      id: '/pay-loan/'
      path: '/pay-loan'
      fullPath: '/pay-loan'
      preLoaderRoute: typeof PayLoanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-application/': {
      id: '/loan-application/'
      path: '/loan-application'
      fullPath: '/loan-application'
      preLoaderRoute: typeof LoanApplicationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center/': {
      id: '/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account/': {
      id: '/delete-account/'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/': {
      id: '/calculator/'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-phone-number/': {
      id: '/add-phone-number/'
      path: '/add-phone-number'
      fullPath: '/add-phone-number'
      preLoaderRoute: typeof AddPhoneNumberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-identity/verify-personal-details': {
      id: '/verify-identity/verify-personal-details'
      path: '/verify-identity/verify-personal-details'
      fullPath: '/verify-identity/verify-personal-details'
      preLoaderRoute: typeof VerifyIdentityVerifyPersonalDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-identity/identity-verified': {
      id: '/verify-identity/identity-verified'
      path: '/verify-identity/identity-verified'
      fullPath: '/verify-identity/identity-verified'
      preLoaderRoute: typeof VerifyIdentityIdentityVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-identity/id-details': {
      id: '/verify-identity/id-details'
      path: '/verify-identity/id-details'
      fullPath: '/verify-identity/id-details'
      preLoaderRoute: typeof VerifyIdentityIdDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-identity/front-id-verification': {
      id: '/verify-identity/front-id-verification'
      path: '/verify-identity/front-id-verification'
      fullPath: '/verify-identity/front-id-verification'
      preLoaderRoute: typeof VerifyIdentityFrontIdVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-identity/face-verification': {
      id: '/verify-identity/face-verification'
      path: '/verify-identity/face-verification'
      fullPath: '/verify-identity/face-verification'
      preLoaderRoute: typeof VerifyIdentityFaceVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-identity/choose-id': {
      id: '/verify-identity/choose-id'
      path: '/verify-identity/choose-id'
      fullPath: '/verify-identity/choose-id'
      preLoaderRoute: typeof VerifyIdentityChooseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-identity/back-id-verification': {
      id: '/verify-identity/back-id-verification'
      path: '/verify-identity/back-id-verification'
      fullPath: '/verify-identity/back-id-verification'
      preLoaderRoute: typeof VerifyIdentityBackIdVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-phone/verify-phone': {
      id: '/update-phone/verify-phone'
      path: '/update-phone/verify-phone'
      fullPath: '/update-phone/verify-phone'
      preLoaderRoute: typeof UpdatePhoneVerifyPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-phone/number-verified': {
      id: '/update-phone/number-verified'
      path: '/update-phone/number-verified'
      fullPath: '/update-phone/number-verified'
      preLoaderRoute: typeof UpdatePhoneNumberVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-up/top-up-main': {
      id: '/top-up/top-up-main'
      path: '/top-up/top-up-main'
      fullPath: '/top-up/top-up-main'
      preLoaderRoute: typeof TopUpTopUpMainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokuen-info/terms-and-conditions': {
      id: '/tokuen-info/terms-and-conditions'
      path: '/tokuen-info/terms-and-conditions'
      fullPath: '/tokuen-info/terms-and-conditions'
      preLoaderRoute: typeof TokuenInfoTermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokuen-info/privacy-policy': {
      id: '/tokuen-info/privacy-policy'
      path: '/tokuen-info/privacy-policy'
      fullPath: '/tokuen-info/privacy-policy'
      preLoaderRoute: typeof TokuenInfoPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-scanner/scan': {
      id: '/qr-scanner/scan'
      path: '/qr-scanner/scan'
      fullPath: '/qr-scanner/scan'
      preLoaderRoute: typeof QrScannerScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods/card-added': {
      id: '/payment-methods/card-added'
      path: '/payment-methods/card-added'
      fullPath: '/payment-methods/card-added'
      preLoaderRoute: typeof PaymentMethodsCardAddedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods/add-card': {
      id: '/payment-methods/add-card'
      path: '/payment-methods/add-card'
      fullPath: '/payment-methods/add-card'
      preLoaderRoute: typeof PaymentMethodsAddCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-loan/review-details': {
      id: '/pay-loan/review-details'
      path: '/pay-loan/review-details'
      fullPath: '/pay-loan/review-details'
      preLoaderRoute: typeof PayLoanReviewDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-loan/pay-through': {
      id: '/pay-loan/pay-through'
      path: '/pay-loan/pay-through'
      fullPath: '/pay-loan/pay-through'
      preLoaderRoute: typeof PayLoanPayThroughRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-loan/loan-paid': {
      id: '/pay-loan/loan-paid'
      path: '/pay-loan/loan-paid'
      fullPath: '/pay-loan/loan-paid'
      preLoaderRoute: typeof PayLoanLoanPaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/empty': {
      id: '/notifications/empty'
      path: '/notifications/empty'
      fullPath: '/notifications/empty'
      preLoaderRoute: typeof NotificationsEmptyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/loan-list': {
      id: '/loans/loan-list'
      path: '/loans/loan-list'
      fullPath: '/loans/loan-list'
      preLoaderRoute: typeof LoansLoanListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-application/loan-details': {
      id: '/loan-application/loan-details'
      path: '/loan-application/loan-details'
      fullPath: '/loan-application/loan-details'
      preLoaderRoute: typeof LoanApplicationLoanDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-application/loan-approved': {
      id: '/loan-application/loan-approved'
      path: '/loan-application/loan-approved'
      fullPath: '/loan-application/loan-approved'
      preLoaderRoute: typeof LoanApplicationLoanApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-application/choose-emi': {
      id: '/loan-application/choose-emi'
      path: '/loan-application/choose-emi'
      fullPath: '/loan-application/choose-emi'
      preLoaderRoute: typeof LoanApplicationChooseEmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account/delete-using-phone': {
      id: '/delete-account/delete-using-phone'
      path: '/delete-account/delete-using-phone'
      fullPath: '/delete-account/delete-using-phone'
      preLoaderRoute: typeof DeleteAccountDeleteUsingPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account/account-deleted': {
      id: '/delete-account/account-deleted'
      path: '/delete-account/account-deleted'
      fullPath: '/delete-account/account-deleted'
      preLoaderRoute: typeof DeleteAccountAccountDeletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills-payment/payment-main': {
      id: '/bills-payment/payment-main'
      path: '/bills-payment/payment-main'
      fullPath: '/bills-payment/payment-main'
      preLoaderRoute: typeof BillsPaymentPaymentMainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-phone-number/phone-number-added': {
      id: '/add-phone-number/phone-number-added'
      path: '/add-phone-number/phone-number-added'
      fullPath: '/add-phone-number/phone-number-added'
      preLoaderRoute: typeof AddPhoneNumberPhoneNumberAddedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/verify-email/': {
      id: '/authentication/verify-email/'
      path: '/authentication/verify-email'
      fullPath: '/authentication/verify-email'
      preLoaderRoute: typeof AuthenticationVerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/registration/': {
      id: '/authentication/registration/'
      path: '/authentication/registration'
      fullPath: '/authentication/registration'
      preLoaderRoute: typeof AuthenticationRegistrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/forgot-password/': {
      id: '/authentication/forgot-password/'
      path: '/authentication/forgot-password'
      fullPath: '/authentication/forgot-password'
      preLoaderRoute: typeof AuthenticationForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/verify-email/email-verified': {
      id: '/authentication/verify-email/email-verified'
      path: '/authentication/verify-email/email-verified'
      fullPath: '/authentication/verify-email/email-verified'
      preLoaderRoute: typeof AuthenticationVerifyEmailEmailVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/registration/create-password': {
      id: '/authentication/registration/create-password'
      path: '/authentication/registration/create-password'
      fullPath: '/authentication/registration/create-password'
      preLoaderRoute: typeof AuthenticationRegistrationCreatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/registration/account-created': {
      id: '/authentication/registration/account-created'
      path: '/authentication/registration/account-created'
      fullPath: '/authentication/registration/account-created'
      preLoaderRoute: typeof AuthenticationRegistrationAccountCreatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/forgot-password/password-changed': {
      id: '/authentication/forgot-password/password-changed'
      path: '/authentication/forgot-password/password-changed'
      fullPath: '/authentication/forgot-password/password-changed'
      preLoaderRoute: typeof AuthenticationForgotPasswordPasswordChangedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/forgot-password/forgot-password-1': {
      id: '/authentication/forgot-password/forgot-password-1'
      path: '/authentication/forgot-password/forgot-password-1'
      fullPath: '/authentication/forgot-password/forgot-password-1'
      preLoaderRoute: typeof AuthenticationForgotPasswordForgotPassword1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SampleRoute: SampleRoute,
  AddPhoneNumberPhoneNumberAddedRoute: AddPhoneNumberPhoneNumberAddedRoute,
  BillsPaymentPaymentMainRoute: BillsPaymentPaymentMainRoute,
  DeleteAccountAccountDeletedRoute: DeleteAccountAccountDeletedRoute,
  DeleteAccountDeleteUsingPhoneRoute: DeleteAccountDeleteUsingPhoneRoute,
  LoanApplicationChooseEmiRoute: LoanApplicationChooseEmiRoute,
  LoanApplicationLoanApprovedRoute: LoanApplicationLoanApprovedRoute,
  LoanApplicationLoanDetailsRoute: LoanApplicationLoanDetailsRoute,
  LoansLoanListRoute: LoansLoanListRoute,
  NotificationsEmptyRoute: NotificationsEmptyRoute,
  PayLoanLoanPaidRoute: PayLoanLoanPaidRoute,
  PayLoanPayThroughRoute: PayLoanPayThroughRoute,
  PayLoanReviewDetailsRoute: PayLoanReviewDetailsRoute,
  PaymentMethodsAddCardRoute: PaymentMethodsAddCardRoute,
  PaymentMethodsCardAddedRoute: PaymentMethodsCardAddedRoute,
  QrScannerScanRoute: QrScannerScanRoute,
  TokuenInfoPrivacyPolicyRoute: TokuenInfoPrivacyPolicyRoute,
  TokuenInfoTermsAndConditionsRoute: TokuenInfoTermsAndConditionsRoute,
  TopUpTopUpMainRoute: TopUpTopUpMainRoute,
  UpdatePhoneNumberVerifiedRoute: UpdatePhoneNumberVerifiedRoute,
  UpdatePhoneVerifyPhoneRoute: UpdatePhoneVerifyPhoneRoute,
  VerifyIdentityBackIdVerificationRoute: VerifyIdentityBackIdVerificationRoute,
  VerifyIdentityChooseIdRoute: VerifyIdentityChooseIdRoute,
  VerifyIdentityFaceVerificationRoute: VerifyIdentityFaceVerificationRoute,
  VerifyIdentityFrontIdVerificationRoute:
    VerifyIdentityFrontIdVerificationRoute,
  VerifyIdentityIdDetailsRoute: VerifyIdentityIdDetailsRoute,
  VerifyIdentityIdentityVerifiedRoute: VerifyIdentityIdentityVerifiedRoute,
  VerifyIdentityVerifyPersonalDetailsRoute:
    VerifyIdentityVerifyPersonalDetailsRoute,
  AddPhoneNumberIndexRoute: AddPhoneNumberIndexRoute,
  CalculatorIndexRoute: CalculatorIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DeleteAccountIndexRoute: DeleteAccountIndexRoute,
  HelpCenterIndexRoute: HelpCenterIndexRoute,
  LoanApplicationIndexRoute: LoanApplicationIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  PayLoanIndexRoute: PayLoanIndexRoute,
  PaymentMethodsIndexRoute: PaymentMethodsIndexRoute,
  ReferAndEarnIndexRoute: ReferAndEarnIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  UpdatePhoneIndexRoute: UpdatePhoneIndexRoute,
  UserProfileIndexRoute: UserProfileIndexRoute,
  VerifyIdentityIndexRoute: VerifyIdentityIndexRoute,
  AuthenticationForgotPasswordForgotPassword1Route:
    AuthenticationForgotPasswordForgotPassword1Route,
  AuthenticationForgotPasswordPasswordChangedRoute:
    AuthenticationForgotPasswordPasswordChangedRoute,
  AuthenticationRegistrationAccountCreatedRoute:
    AuthenticationRegistrationAccountCreatedRoute,
  AuthenticationRegistrationCreatePasswordRoute:
    AuthenticationRegistrationCreatePasswordRoute,
  AuthenticationVerifyEmailEmailVerifiedRoute:
    AuthenticationVerifyEmailEmailVerifiedRoute,
  AuthenticationForgotPasswordIndexRoute:
    AuthenticationForgotPasswordIndexRoute,
  AuthenticationRegistrationIndexRoute: AuthenticationRegistrationIndexRoute,
  AuthenticationVerifyEmailIndexRoute: AuthenticationVerifyEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
